name: Python application

on: 
  push:
    branches:    
    # Push events on main branch
    - 'main'
    - 'release-candidates'
    - '!dev'
    - '!bug/**'
    paths:
    - 'python/**'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/webapp/requirements.txt
    - name: Build and Push Image
      env:
        APP_VERSION: "v1.2"
      run: |
        cd ./python
        echo "${{ secrets.DOCKERHUB }}" | docker login -u falenn --password-stdin
        docker image build \
            --build-arg version=$APP_VERSION \
            --build-arg APP_VERSION=$APP_VERSION \
            -t falenn/python-gitops:$APP_VERSION .
        docker push falenn/python-gitops:$APP_VERSION
