name: Python application

on: 
  push:
    branches:    
    # Push events on main branch
    - 'main'
    - 'releases/**'
    - '!dev'
    - '!bug/**'
    paths:
    - 'python/*'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build and Push Image
      env:
        VERSION: "v1.0"
      run: |
        cd ./python
        echo "${{ secrets.DOCKERHUB }}" | docker login -u falenn --password-stdin
        docker image build --build-arg version=$VERSION -t falenn/python-gitops:$VERSION .
        docker push falenn/python-gitops:$VERSION
